<a href="https://colab.research.google.com/github/Zeroo2002/Zeroo2002/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np      #We can use any name instead of 'np'

print(np.full(10,2)) #creating array with any number of length 10
print(np.zeros(10, dtype='int')) #creating array with zeros of length 10
print(np.ones(10, dtype='int')) #creating array with zeros length 10
print(np.full((3,5),"Ringki")) #creating an array with pre-defined values
print(np.arange(0, 20, 2)) #creating an array with a set sequence
print(np.arange(0, 21, 2)) #creating an array with a set sequence
print(np.linspace(0, 1, 5)) #create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
print(np.linspace(0, 2, 3)) #create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
print(np.eye(3)) #creates an identity matrix of axa where a = given value

[2 2 2 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[['Ringki' 'Ringki' 'Ringki' 'Ringki' 'Ringki']
 ['Ringki' 'Ringki' 'Ringki' 'Ringki' 'Ringki']
 ['Ringki' 'Ringki' 'Ringki' 'Ringki' 'Ringki']]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  2  4  6  8 10 12 14 16 18 20]
[0.   0.25 0.5  0.75 1.  ]
[0. 1. 2.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
#ACCESSING ARRAY ELEMENTS

x1 = np.array([4, 3, 2, 13, 8, 4])

print(x1)    #prints the array x1
print(x1[0], x1[5]) #accesing the elements of array
print(x1[-1], x1[-4])

x2 = np.array([[3, 7, 5, 5],
               [0, 1, 5, 9],
               [3, 0, 5, 4]])

print(x2)
print(x2[2,3]) #2nd row 3rd column
print(x2[-2,-1])  #last 2nd row last column

[ 4  3  2 13  8  4]
4 4
4 2
[[3 7 5 5]
 [0 1 5 9]
 [3 0 5 4]]
4
9


In [53]:
#array slicing in single dimension

x = np.arange(10)
print(x)

print(x[:5])   #from start to (5-1) index
print(x[4:])   #from 4th index to end

print(x[4:7])    #from 4th index to 6th index

print(x[: : 2])   #prints from start to end skipping every 2nd element

print(x[: : -1])  #prints from end to start or reverse the array

print(x[1: : 2])  #prints from index 1 to end skipping every 2nd element

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[4 5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
[1 3 5 7 9]


In [ ]:
#Array Slicing in Multidimensional array

x3 = np.array([[3, 7, 5, 0],
               [0, 1, 2, 9],
               [3, 0, 6, 4]])

print(x3)

print(x3.shape)   #returns the dimension of the array
print(x3[0:2])   #rows including from index 0 but excluding index 2
print(x3[0:2, 1:3])    #First 2 rows, 1st(index 2) and 2nd(index 3) column

print(x3[2])   #only row of index 2
print(x3[:, 2])  #only column



In [70]:
#Finding dimension of 1xn array

x1 = np.array([[1,2,3]])
print(x1.shape)

(1, 3)


In [74]:
#Creating 3D array in numpy

x3 = np.array([[[1,2,3],                   #Here [[1,2,3], [3,4,5]] is 1st slice
                [3,4,1]],

                [[5,6,2],                  #Here [[5,6,2], [7,8,4]] is 2nd slice
                [7,8,4]]])

print(x3)
print(x3.shape)
print(x3[1, 0, 1])     #slice, row, column


[[[1 2 3]
  [3 4 1]]

 [[5 6 2]
  [7 8 4]]]
(2, 2, 3)
6


In [100]:
#Splitting and COncatenantion of Arrays(Notes Version)


#Concatenation

x1 = np.arange(0, 10, 2)
x2 = np.arange(10, 20, 2)


print(x1, x2)

#x3 = np.concatenate([x1, x2], axis=0)     #concatenates given arrays
x3 = np.stack([x1, x2], axis =0)           #stacks given arrays
#x3 = np.vstack([x1,x2])                   #stacks given arrays vertically
#x3 = np.hstack([x1,x2])                    #stacks given arrays horizontally or simply concatenates
print(x3)



[0 2 4 6 8] [10 12 14 16 18] [20 22 24 26 28]
[[ 0 10 20]
 [ 2 12 22]
 [ 4 14 24]
 [ 6 16 26]
 [ 8 18 28]]


In [ ]:
#Splitting and COncatenantion of Arrays(Trial Version)


#Concatenation

x1 = np.arange(0, 10, 2)
x2 = np.arange(10, 20, 2)
x3 = np.arange(20, 30, 2)

print(x1, x2, x3)

#x3 = np.concatenate([x1, x2], axis=0)     #concatenates given arrays
#x3 = np.stack([x1, x2, x3], axis =0)
x3 = np.stack([x1, x2, x3], axis =1)         #stacks given arrays
#x3 = np.vstack([x1,x2])                   #stacks given arrays vertically
#x3 = np.hstack([x1,x2])                    #stacks given arrays horizontally or simply concatenates
print(x3)



In [127]:
#2D array  concatenation

x1 = np.array([[1,2,3,4], [5,6,7,8]])
x2 = np.array([[9,10,11,12],[13,14,15,16]])

#print(x1,x2)

x3 = np.concatenate([x1,x2], axis = 0)
x3 = np.hstack([x1, x2])
#x3 = np.vstack([x1, x2])
print(x3, x3.shape)
#np.hsplit(x3, [2])                      #splits an array into multiple sub-arrays horizontally

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]] (2, 8)


In [126]:
#Array Splitting

x1 = np.arange(0,15,2)
print(x1)

x2 = np.split(x1,[3])   #splits the array after index 2
print(x2)

x2 = np.array_split(x1, 3)  #splits the entire array into arrays of size 3
print(x2)

[ 0  2  4  6  8 10 12 14]
[array([0, 2, 4]), array([ 6,  8, 10, 12, 14])]
[array([0, 2, 4]), array([ 6,  8, 10]), array([12, 14])]


In [ ]:
#Array Reshaping
x3 = np.array([[[1,2,3],                   #Here [[1,2,3], [3,4,5]] is 1st slice
                [3,4,1]],

                [[5,6,2],                  #Here [[5,6,2], [7,8,4]] is 2nd slice
                [7,8,4]]])

print(x3)


In [115]:
np4 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])

print(np4.shape)

(4, 4)


In [120]:
x = np.array([[1,2,5,0],
                [5,9,7,8],
                [9,0,2,1],
                [1,4,5,6]])

#finding the unique values
unique_values = np.unique(x)
print(unique_values)

#printing the frequencies of each element


[0 1 2 4 5 6 7 8 9]
